### PR TITLE
new file format Parquet Files

### PR DESCRIPTION
**Pull request by cambrown52**
Added a file reader for parquet file format along with associated tests. Added such that parquet files can be viewed in pydatview. Parquet files are read by pandas which relies on pyarrow package for reading parquet files. Pyarrow added to list of optional dependencies. A dummy parquet file with a small amount of data was added for unit test.

### CODE REVIEW

**Comment by ebranlard** [comment]
Hi Cam, Thanks for adding that, including adding a test! The current travis setup only installs the "requirements.txt". I can't remember why I have introduced the optional requirements.. I'm not sure how big is pyarrow, but feel free to add it to the requirements.txt, or add a line in .travis.yml so that travis installs the optional requirements.

**Comment by cambrown52** [comment]
I looked at pyarrow on pypi. The wheels are between about 15-20MB depending on the python version and os.
https://pypi.org/project/pyarrow/#files

Is it ok to add to requirements.txt? Do you like it to be pinned to a specific version?

**Comment by ebranlard** [comment]
Yes, go ahead, it seems like a useful, generic format. I don't think there is a need for a specific version. Thanks again!

**Comment by cambrown52** [comment]
I put the pyarrow package into requirements.txt and now the tests seem to have succeeded!

**Pull request merged**
