### PR TITLE
Fixing key bug in induction files

### PR DESCRIPTION
**Pull request by jennirinker**
I used floats as the keys, which makes PyDatView vomit on loading. This changes them to strings and updates the tests.

Sorry I didn't catch this in my first PR.

### CODE REVIEW

**Comment by ebranlard** [comment]
hahaha, I've actually updated pyDatView to force keys to be string :)

**Comment by jennirinker** [comment]
Well damn that's smart. But I need to add some sorting on the load or the wind speeds can be out of order...so let me do that. I'm really not testing my work thoroughly enough before asking for a PR, I'm just too excited.

**Comment by ebranlard** [comment]
No worries. I'll happily accept your changes, whatever you think is more convenient.

**Comment by jennirinker** [comment]
I think forcing keys to be strings is fine. I'll leave the string logic in weio. I just need to construct my dfs more intelligently so the wind speeds are in order. (Current problem is, e.g., "11.0" comes before "3.0".) I'll let you know when I think I've pushed a solution.

**Comment by jennirinker** [comment]
Alright, wsp sorting is added and it behaves quite sexy on my side. I mean, look at these beautiful angles of attack.

image

**Comment by ebranlard** [comment]
pyDatView should also have a "sortbyname" feature, but it's still a bit beta. 
Looking good! 
I'll wait a day or so and merge this, is that ok? Just in case you want to push more things here.

**Comment by jennirinker** [comment]
Yes, please wait. I'm a bit too rushed on things.

**Comment by jennirinker** [comment]
So I've reverted back to loading only the files that are dragged in, which is the best behavior, IMO. But now I don't like how PyDatView is naming the files on load. I don't know how it's choosing the file names, but it differs depending on which files you drag in. And re-sorting doesn't work. It's a bit frustrating, I was hoping to finish this but now I don't have any more time to work on it. :(

**Pull request merged**
